version: "3"
services:
  app:
    build: .
    restart: always
    network_mode: "host"
    image: pabloszx/cotiza-facil
    environment:
      DB_URL: ${DB_URL}
      COOKIE_KEY: ${COOKIE_KEY}
      PORT: ${PORT}
  watchtower:
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 60
    environment:
      WATCHTOWER_NOTIFICATIONS: "slack"
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: "https://hooks.slack.com/services/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"
      WATCHTOWER_NOTIFICATION_SLACK_ICON_EMOJI: ":whale:"
      WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: "Watchtower awesome-templates"
      WATCHTOWER_NOTIFICATION_SLACK_CHANNEL: "#awesome-templates"
